# Compile project on Ubuntu
name: Ubuntu
on:
  push:
    paths:
      - "**"
      - "!.github/**"
      - ".github/workflows/Ubuntu.yml"
      - "!scripts/"
      - "scripts/actions/install_cuda_ubuntu.sh"
      - "!*.md"
jobs:
  build:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      # explicit include-based build matrix, of known valid options
      self-hosted:
        include:
          # 22.04 supports CUDA 11.7+
          - os: ubuntu-22.04
            cuda: "12.0"
            gcc: 11
          - os: ubuntu-22.04
            cuda: "11.8"
            gcc: 10
          - os: ubuntu-22.04
            cuda: "11.7"
            gcc: 10
          # 20.04 supports CUDA 11.0+
          - os: ubuntu-20.04
            cuda: "11.6"
            gcc: 10
          - os: ubuntu-20.04
            cuda: "11.5"
            gcc: 10
          - os: ubuntu-20.04
            cuda: "11.4"
            gcc: 10
          - os: ubuntu-20.04
            cuda: "11.3"
            gcc: 10
          - os: ubuntu-20.04
            cuda: "11.2"
            gcc: 10
          - os: ubuntu-20.04
            cuda: "11.0"
            gcc: 9
    env:
      build_dir: "build"
      config: "Release"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""
      - run: conda install -c conda-forge boost swig numpy
      - run: echo "$CONDA_PREFIX"
      - name: Install CUDA
        env:
          cuda: ${{ self-hosted.cuda }}
        run: |
          chmod +x scripts/actions/install_cuda_ubuntu.sh
          ./scripts/actions/install_cuda_ubuntu.sh
        shell: bash

      # Specify the correct host compilers
      - name: Install/Select gcc and g++
        run: |
          sudo apt-get install -y gcc-${{ self-hosted.gcc }} g++-${{ self-hosted.gcc }}
          echo "CC=/usr/bin/gcc-${{ self-hosted.gcc }}" >> $GITHUB_ENV
          echo "CXX=/usr/bin/g++-${{ self-hosted.gcc }}" >> $GITHUB_ENV
          echo "CUDAHOSTCXX=/usr/bin/g++-${{ self-hosted.gcc }}" >> $GITHUB_ENV
      - name: Configure cmake
        id: configure
        run: cmake . -B ${{ env.build_dir }} -DCMAKE_BUILD_TYPE=${{ env.config }} -DCONDA_DIR=$CONDA_PREFIX -DCMAKE_CUDA_ARCHITECTURES=52

      - name: Configure Error Processing
        if: ${{ failure() && steps.configure.outcome == 'failure' }}
        run: |
          if [[ -d "${{ env.build_dir }}" ]]; then
            pushd "${{ env.build_dir }}"
            if [[ -f "CMakeFiles/CMakeOutput.log" ]]; then
              echo "---- CMakeFiles/CMakeOutput.log"
              cat CMakeFiles/CMakeOutput.log
              echo "----"
            fi
            if [[ -f "CMakeFiles/CMakeError.log" ]]; then
              echo "---- CMakeFiles/CMakeError.log"
              cat CMakeFiles/CMakeError.log
              echo "----"
            fi
          fi
      - name: Build everything else
        working-directory: ${{ env.build_dir }}
        run: |
          cmake --build . --target all -j
          make python
      - name: Run tests
        working-directory: ${{ env.build_dir }}
        run: ctest --output-on-failure
